SELECT TOP (1000) [Id]
      ,[AlunoMatriculadoId]
      ,[DataCadastro]
      ,[DescricaoPropina]
      ,[PrecoPropina]
      ,[AnoLetivo]
      ,[Situacao]
      ,[PagamentoPropinaId]
  FROM [JANGOBD].[dbo].[Propinas]
