SELECT DATEPART(DAY, CAST('04/10/1980'AS DATETIME)) AS 'RETORNAR O NÚMERO QUE CORRESPONDE O MES'
SELECT  DATEPART(MONTH, GETDATE()) AS 'RETORNAR O NÚMERO QUE CORRESPONDE O MES'
-- ----------------------------------------------------------------------------
USE [JANGOBD]
GO
SELECT Nome, DATEPART(DD, DataCadastro) AS 'DIA DE CADASTRO',
DATEPART(MM, DataCadastro) AS 'MES DE CADASTRO',
DATENAME(MM, DataCadastro) AS 'NOME DO MES DE CADASTRO',
DATEPART(YYYY, DataCadastro) AS 'ANO DE CADASTRO'
  FROM [JANGOBD].[dbo].[AlunoMatriculados]
-- ----------------------------------------------------------------------------
--SELECT DATEPART(DAY, GETDATE()) AS 'DIA ATUAL'
--SELECT  DATEPART(MONTH, GETDATE()) AS 'MÊS ATUAL'
--SELECT  DATEPART(YY, GETDATE()) AS 'ANO ATUAL'
SELECT  DATEDIFF(YY,'1980-10-04', GETDATE()) AS 'IDADE'
SELECT  DATEDIFF(MM,'1980-10-04', GETDATE()) AS 'MESES DE VIDA'
SELECT  DATEDIFF(DD,CAST('04/10/1980'AS DATETIME), GETDATE()) AS 'DIAS DE VIDA'
SELECT  DATEDIFF(WK, CAST('04/10/1980'AS DATETIME), GETDATE()) AS 'DIAS DE VIDA'
SELECT  DATEDIFF(HH,GETUTCDATE(), GETDATE()) AS 'HORA LEGAL DE ANGOLA'

SELECT  DATEDIFF(DD, GETDATE(),CAST('01/01/2025'AS DATETIME)) AS 'QUANTOS DIAS FALTAM PARA A DATA (01/01/2025)?'
SELECT  CONVERT(VARCHAR(10), '12/03/2025',103) AS 'DATA'
SELECT  CONVERT(VARCHAR(10), GETDATE(),103) AS 'DATA DE HOJE'
SELECT  CONVERT(VARCHAR(10), GETDATE(),108) AS 'HORA MINUTOS E SEGUNGOS'
SELECT  CONVERT(VARCHAR(5), GETDATE(),108) AS 'HORA E MINUTOS'
SELECT  CONVERT(VARCHAR(2), GETDATE(),108) AS 'HORA'
SELECT  DATEDIFF(DD,GETDATE(), GETDATE()) AS 'HORA LEGAL DE ANGOLA'
--SELECT CAST('04/10/1980'AS DATETIME)
  --SELECT GETDATE() AS 'DATA ATUAL'